import { Mail, Search } from "lucide-react";
import { notFound } from "next/navigation";
import { auth } from "@/auth";
import { deleteNewsletterSubscriberAction, updateNewsletterStatusAction } from "@/features/newsletter/server/newsletter.actions";
import { countNewsletterSubscribers, findNewsletterSubscribers } from "@/features/newsletter/server/newsletter.repository";

const dateFormat = new Intl.DateTimeFormat("vi-VN", { day: "2-digit", month: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit" });
type PageProps = { searchParams: Promise<{ q?: string; status?: string }> };

export default async function NewsletterAdminPage({ searchParams }: PageProps) {
  const session = await auth();
  if (session?.user?.role !== "ADMIN") notFound();
  const filters = await searchParams;
  const status = filters.status === "ACTIVE" || filters.status === "UNSUBSCRIBED" ? filters.status : undefined;
  const [subscribers, counts] = await Promise.all([findNewsletterSubscribers({ query: filters.q?.trim(), status }), countNewsletterSubscribers()]);
  return <div className="space-y-6">
    <section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="font-mono text-xs font-bold text-[#8B5CF6]">NEWSLETTER</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight">Email đăng ký nhận tin</h1><p className="mt-2 text-sm text-[#64748B]">Tìm kiếm và quản lý tối đa 200 đăng ký gần nhất.</p></div><div className="flex items-center gap-2 rounded-full border-2 border-[#1E293B] bg-white px-4 py-2 text-sm font-bold shadow-pop-sm"><Mail className="h-4 w-4 text-[#8B5CF6]" />{counts.active} đang nhận tin</div></section>
    <section className="grid gap-3 sm:grid-cols-3">{[["Tổng đăng ký", counts.total], ["Đang hoạt động", counts.active], ["Đã dừng nhận", counts.unsubscribed]].map(([label, value]) => <div key={String(label)} className="border-b-2 border-[#1E293B] bg-white p-4"><p className="text-sm font-bold text-[#64748B]">{label}</p><p className="mt-2 text-3xl font-extrabold">{Number(value).toLocaleString("vi-VN")}</p></div>)}</section>
    <form className="grid gap-3 rounded-2xl border-2 border-[#1E293B] bg-white p-4 shadow-pop-sm md:grid-cols-[1fr_auto_auto]"><label className="relative"><span className="sr-only">Tìm email</span><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#64748B]" /><input name="q" type="search" defaultValue={filters.q} placeholder="Tìm theo địa chỉ email" className="w-full rounded-xl border-2 border-[#1E293B] bg-[#FFFDF5] py-2.5 pl-10 pr-3 text-sm font-medium outline-none focus:ring-2 focus:ring-[#8B5CF6]" /></label><select name="status" defaultValue={status ?? ""} className="rounded-xl border-2 border-[#1E293B] bg-[#FFFDF5] px-3 py-2.5 text-sm font-bold outline-none focus:ring-2 focus:ring-[#8B5CF6]"><option value="">Tất cả trạng thái</option><option value="ACTIVE">Đang nhận tin</option><option value="UNSUBSCRIBED">Đã dừng nhận</option></select><button className="rounded-full border-2 border-[#1E293B] bg-[#8B5CF6] px-5 py-2.5 text-sm font-bold text-white shadow-pop-sm active:translate-y-px">Lọc danh sách</button></form>
    <section className="overflow-hidden rounded-2xl border-2 border-[#1E293B] bg-white shadow-pop-sm">{subscribers.length ? <div className="divide-y-2 divide-[#E2E8F0]">{subscribers.map((subscriber) => <article key={subscriber.id} className="grid gap-4 p-5 md:grid-cols-[minmax(240px,1fr)_170px_130px_auto] md:items-center"><div className="min-w-0"><p className="truncate font-bold">{subscriber.email}</p><p className="mt-1 text-xs text-[#64748B]">Nguồn: {subscriber.source}</p></div><p className="text-sm text-[#64748B]">{dateFormat.format(subscriber.subscribed_at)}</p><span className={`w-fit rounded-md border px-2 py-1 text-xs font-extrabold ${subscriber.status === "ACTIVE" ? "border-[#059669] bg-[#D1FAE5] text-[#047857]" : "border-[#94A3B8] bg-[#F1F5F9] text-[#475569]"}`}>{subscriber.status === "ACTIVE" ? "Đang nhận" : "Đã dừng"}</span><div className="flex flex-wrap gap-2 md:justify-end"><form action={updateNewsletterStatusAction}><input type="hidden" name="id" value={subscriber.id} /><input type="hidden" name="status" value={subscriber.status === "ACTIVE" ? "UNSUBSCRIBED" : "ACTIVE"} /><button className="rounded-lg border-2 border-[#1E293B] bg-white px-3 py-2 text-xs font-bold active:translate-y-px">{subscriber.status === "ACTIVE" ? "Tạm dừng" : "Kích hoạt"}</button></form><form action={deleteNewsletterSubscriberAction}><input type="hidden" name="id" value={subscriber.id} /><button className="rounded-lg border-2 border-[#1E293B] bg-[#FFF1F2] px-3 py-2 text-xs font-bold text-[#BE123C] active:translate-y-px">Xóa</button></form></div></article>)}</div> : <div className="p-12 text-center"><Mail className="mx-auto h-8 w-8 text-[#94A3B8]" /><p className="mt-3 font-bold">Chưa có email phù hợp.</p><p className="mt-1 text-sm text-[#64748B]">Đăng ký từ trang Home sẽ xuất hiện tại đây.</p></div>}</section>
  </div>;
}
