import Link from "next/link";
import { Newspaper, PenLine, Plus } from "lucide-react";
import { getAdminPostList } from "@/features/content/server/post-editor.service";
import { AdminPostRowActions } from "@/features/content/components/admin-post-row-actions";
import { auth } from "@/auth";
import { notFound } from "next/navigation";
import { canUseAuthorPermission } from "@/features/admin/server/author-permissions";

export default async function AdminPostsPage() {
  const session = await auth();
  if (!session?.user || !(await canUseAuthorPermission(session.user, "writePosts"))) notFound();
  const posts = await getAdminPostList(session.user.role === "AUTHOR" ? session.user.id : undefined);
  return <div className="space-y-6"><section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="font-mono text-xs font-bold text-[#8B5CF6]">NỘI DUNG</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight">Bài viết</h1><p className="mt-2 text-sm text-[#64748B]">Quản lý bài nháp và bài đã xuất bản trong database.</p></div><div className="flex flex-wrap gap-2"><Link href="/admin/news/new" className="inline-flex items-center justify-center gap-2 rounded-lg border-2 border-[#1E293B] bg-white px-4 py-2.5 text-sm font-extrabold text-[#1E293B]"><Newspaper className="h-4 w-4" />Viết tin tức</Link><Link href="/admin/posts/new" className="inline-flex items-center justify-center gap-2 rounded-lg border-2 border-[#1E293B] bg-[#FBBF24] px-4 py-2.5 text-sm font-extrabold text-[#1E293B]"><Plus className="h-4 w-4" />Viết bài mới</Link></div></section><section className="overflow-hidden rounded-2xl border-2 border-[#1E293B] bg-white shadow-pop-sm">{posts.length ? <div className="overflow-x-auto"><table className="min-w-[760px] w-full text-left text-sm"><thead className="bg-[#F8FAFC] text-xs font-extrabold text-[#64748B]"><tr><th className="px-5 py-3">Tiêu đề</th><th className="px-5 py-3">Chuyên mục</th><th className="px-5 py-3">Trạng thái</th><th className="px-5 py-3">Cập nhật</th><th className="px-5 py-3"><span className="sr-only">Thao tác</span></th></tr></thead><tbody>{posts.map((post) => { const editable = !post.content_mdx.startsWith("Content is managed in src/content/posts/"); return <tr key={post.id} className="border-t border-[#E2E8F0]"><td className="px-5 py-4"><Link href={post.status === "PUBLISHED" ? `/posts/${post.slug}` : `/admin/posts/${post.slug}/edit`} className="font-extrabold text-[#1E293B] hover:text-[#6D28D9]">{post.title}</Link><p className="mt-1 font-mono text-xs text-[#64748B]">/{post.slug}</p></td><td className="px-5 py-4 text-[#475569]">{post.categories.name}</td><td className="px-5 py-4"><span className={`rounded-md px-2 py-1 text-xs font-extrabold ${post.status === "PUBLISHED" ? "bg-[#DCFCE7] text-[#166534]" : "bg-[#FEF3C7] text-[#92400E]"}`}>{post.status === "PUBLISHED" ? "Đã xuất bản" : "Bản nháp"}</span></td><td className="px-5 py-4 text-[#475569]">{new Intl.DateTimeFormat("vi-VN", { dateStyle: "medium" }).format(post.updated_at)}</td><td className="px-5 py-4">{editable ? <AdminPostRowActions slug={post.slug} kind="article" /> : <span className="text-xs font-bold text-[#64748B]">Quản lý từ source</span>}</td></tr>; })}</tbody></table></div> : <div className="px-6 py-14 text-center"><PenLine className="mx-auto h-10 w-10 text-[#A78BFA]" /><h2 className="mt-4 text-lg font-extrabold">Chưa có bài viết trong database</h2><Link href="/admin/posts/new" className="mt-3 inline-flex font-bold text-[#6D28D9] hover:underline">Viết bài đầu tiên</Link></div>}</section></div>;
}
